### ISSUE TITLE
not able to make dump_sys generate symbol file

### ISSUE THREAD

**Issue by vinayKs21** [Unvanquished/breakpad#10]
I am able to generate the ```dmp``` file for ```mingw Qt``` application, but when I tried to run ```dump_sys```, I am always getting the below error 
```
CoCreateInstance CLSID_DiaSource {E6756135-1E65-4D17-8576-610761398C3C} failed (msdia*.dll unregistered?)
Open failed
```
Even I downloaded ```msdia80.dll msdia90.dll msdia100.dll, msdia120.dll msdia.140.dll``` and registered all of them in my windows system. But still it is showing me the same error. 
Please help

**Comment by slipher** [comment]
With Daemon Engine we don't use Breakpad's Visual Studio toolchain. So you'd be better off asking on the Chromium upstream.
