### ISSUE TITLE
Does not work for mingw symbol extraction on Linux

### ISSUE THREAD

**Issue by hhyyrylainen** [Unvanquished/breakpad#7]
I'm trying to extract debug symbols from an .exe (compiled with mingw) on Linux, and this looked promising. However, after I've compiled the linux dump_syms executable (which gets compiled if I do the configure and make on Linux) it still reports "Failed to write symbol file."
Should this work? Or are the patches in this repo just for the *Windows* version of the symbol dump tool?

**Comment by slipher** [comment]
Windows symbolization on a Linux host works. You just need to pick the right dump_syms binary based on the *target* architecture. See [here](https://github.com/Unvanquished/release-scripts/blob/f31e8e1f1b0b617ee7af3d97d0854821dbb04b92/build-release#L288).

For some context, https://github.com/jon-turney/google-breakpad is our upstream, which adds the MinGW support lacking in the Chromium version. But it only works on Windows hosts. In this repo we additionally "add support" for Linux hosts, by uncommenting it in the makefile :stuck_out_tongue:

**Comment by hhyyrylainen** [comment]
Does that mean I need to somehow tell configure and make to use mingw to compile? As there are no compiled files in `src/tools/windows/dump_syms`

**Comment by slipher** [comment]
No. The folder is called `dump_syms_dwarf`

**Comment by hhyyrylainen** [comment]
I didn't realize the right folder to look in was `src/tools/windows/dump_syms_dwarf` I found it now. 
Might be good to clarify in the readme that the special dump_sums binary is not in the standard folder.
I didn't have a change to test yet but will it be problematic regarding doing stackwalk as the module identifier is given as `000000000000000000000000000000000` in the symbols dumped?

(I was just about to write an update to my previous message)

**Comment by slipher** [comment]
You have to put a linker flag `-Wl,--build-id` to get a module identifier.

I have some sort of instructions at https://gist.github.com/slipher/ff47754b70778eb0a7c5

**Comment by hhyyrylainen** [comment]
Ah awesome, thanks. I'll think of something (perhaps source code zip hash... edit: looks like it will be automatically set) to pass along there.

This issue can be closed unless it is helpful in reminding to clarify how all of this works in the readme file.

**Comment by hhyyrylainen** [comment]
Actually if you don't mind answering one more question, is it required to have a special version of the breakpad library compiled into the Windows executable built by MinGW or is it enough to dump the symbols with this special version (and otherwise just use the default breakpad, as that has many months of newer commits than this repo)?

**Comment by slipher** [comment]
I don't know.

**Comment by hhyyrylainen** [comment]
I've now tested this and it doesn't seem to be required, so I can use the vanilla breakpad source to compile the crash client and from this repo I just need to compile the dump_syms executable that I only need on my development machine.
